version: "3.9"

services:
  streamlit:
    build: .
    container_name: streamlit_seguimientocontainer
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      AUTH_USERS: "${AUTH_USERS}"
    command:
      [
        "streamlit",
        "run",
        "seguimiento.py",
        "--server.port=8501",
        "--server.address=0.0.0.0",
      ]
